# See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

name: PR Receive
on:
  pull_request_target:

permissions:
  contents: read

jobs:
  pr-target:
    runs-on: ubuntu-latest
    if: github.repository == 'llvm/llvm-project' &&
        github.event.pull_request.commits < 4
    steps:
      - name: Store PR Information
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR

      - uses: actions/upload-artifact@v3
        with:
          name: pr
          path: pr/
